### ISSUE TITLE
Setup Travis CI testing of list

### ISSUE THREAD

**Issue by zeyla** [dabbotorg/radios#11]
We should probably test this using rust's TOML library since the worker parsing this is the most important.

**Comment by Proximyst** [comment]
Is that not what these are?

https://github.com/dabbotorg/radios/blob/master/.travis.yml#L13
https://github.com/dabbotorg/radios/blob/master/src/lib.rs#L23-L26

**Comment by zeyla** [comment]
Yep, forgot to close this, thanks.
